# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        java: [ '8', '11', '13', '15', '17' ]
    name: Test on ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml
